<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Expense.Domain\Expense.Domain.csproj" />
    <ProjectReference Include="..\..\Shared.Exceptions\Shared.Exceptions.csproj" />
    <ProjectReference Include="..\..\Shared.Common\Shared.Common.csproj" />
    <ProjectReference Include="..\..\Shared.Logging\Shared.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
